[package]
name = "stable-diffusion"
version = "0.1.0"
edition = "2021"

[features]
wgpu-backend = ["burn-wgpu"]

[dependencies.burn-wgpu]
package = "burn-wgpu"
version = "0.9.0"
optional = true

[dependencies]
anyhow = "1.0.75"
burn = "0.9.0"
clap = { version = "4.4.6", features = ["derive"] }

