[package]
name = "diffusers-burn"
version = "0.1.0"
edition = "2021"

[features]
wgpu-backend = ["burn-wgpu"]

[dependencies.burn-wgpu]
package = "burn-wgpu"
version = "0.11.0"
optional = true

[dependencies]
anyhow = "1.0.75"
burn = "0.11.0"
burn-ndarray = "0.11.0"
burn-tch = "0.11.0"
clap = { version = "4.4.7", features = ["derive"] }
num-traits = "0.2.17"
serde = { version = "1.0.192", features = ["derive"] }

[patch.crates-io]
burn-wgpu = { git = "https://github.com/Tracel-AI/burn", rev = "be5bb33" }
burn = { git = "https://github.com/Tracel-AI/burn", rev = "be5bb33" }
burn-ndarray = { git = "https://github.com/Tracel-AI/burn", rev = "be5bb33" }
burn-tch = { git = "https://github.com/Tracel-AI/burn", rev = "be5bb33" }
