[package]
name = "diffusers-burn"
version = "0.1.0"
edition = "2021"

[features]
default = ["burn/default", "std"]

std = ["burn/std"]

ndarray = ["burn-ndarray", "burn/ndarray"]
ndarray-no-std = ["burn-ndarray", "burn/ndarray-no-std"]
ndarray-blas-accelerate = ["burn-ndarray", "burn/ndarray-blas-accelerate"]

torch = ["burn-tch", "burn/tch"]
wgpu = ["burn-wgpu", "burn/wgpu"]

[dependencies]
burn = { version = "0.11.0", default-features = false }
burn-ndarray = { version = "0.11.0", default-features = false, optional = true }
burn-tch = { version = "0.11.0", default-features = false, optional = true }
burn-wgpu = { version = "0.11.0", default-features = false, optional = true }
num-traits = { version = "0.2.17", default-features = false }
serde = { version = "1.0.192", default-features = false, features = ["derive", "alloc"] }

[patch.crates-io]
burn-wgpu = { git = "https://github.com/Tracel-AI/burn", rev = "f0c75aa7482512b7c9a05f70da095a181ad4638e" }
burn = { git = "https://github.com/Tracel-AI/burn", rev = "f0c75aa7482512b7c9a05f70da095a181ad4638e" }
burn-ndarray = { git = "https://github.com/Tracel-AI/burn", rev = "f0c75aa7482512b7c9a05f70da095a181ad4638e" }
burn-tch = { git = "https://github.com/Tracel-AI/burn", rev = "f0c75aa7482512b7c9a05f70da095a181ad4638e" }
