[package]
name = "diffusers-burn"
version = "0.1.0"
edition = "2021"

[features]
wgpu = ["burn-wgpu"]
torch = ["burn-tch"]

[dependencies.burn-wgpu]
package = "burn-wgpu"
version = "0.11.0"
optional = true

[dependencies.burn-tch]
package = "burn-tch"
version = "0.11.0"
optional = true

[dependencies]
anyhow = "1.0.75"
burn = "0.11.0"
burn-ndarray = "0.11.0"
clap = { version = "4.4.7", features = ["derive"] }
serde = { version = "1.0.192", features = ["derive"] }

[patch.crates-io]
burn-wgpu = { git = "https://github.com/Tracel-AI/burn", rev = "60c24430c6d4685032d9e351a537eded7da1a35c" }
burn = { git = "https://github.com/Tracel-AI/burn", rev = "60c24430c6d4685032d9e351a537eded7da1a35c" }
burn-ndarray = { git = "https://github.com/Tracel-AI/burn", rev = "60c24430c6d4685032d9e351a537eded7da1a35c" }
burn-tch = { git = "https://github.com/Tracel-AI/burn", rev = "60c24430c6d4685032d9e351a537eded7da1a35c" }
