name: validate
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:    
  rustfmt-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt
    - name: Run cargo fmt
      run: cargo fmt -- --check
    # - name: Run cargo clippy
      # run: cargo clippy -- -D warnings
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest]
        feature: ['default', 'wgpu', 'torch']
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        rustflags: "" # Disable when we're ready
    - name: Test
      run: cargo test --features ${{ matrix.feature }}
